### ISSUE TITLE
Can't add module due to .git repo in release on npm (got workaround)

### ISSUE THREAD

**Issue by OliverHabersetzer** [colxi/midi-parser-js#10]
# The Problem

I noticed when executing `npm i midi-parser-js` I get the following error message:

```bash
[wurstbrohd@wurstbrohd midi-converter]$ npm i midi-parser-js
npm ERR! path /home/wurstbrohd/semester-6/fp/fp-project/extra-tools/midi-converter/node_modules/midi-parser-js
npm ERR! code EISGIT
npm ERR! git /home/wurstbrohd/semester-6/fp/fp-project/extra-tools/midi-converter/node_modules/midi-parser-js: Appears to be a git repo or submodule.
npm ERR! git     /home/wurstbrohd/semester-6/fp/fp-project/extra-tools/midi-converter/node_modules/midi-parser-js
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wurstbrohd/.npm/_logs/2019-06-14T16_07_03_825Z-debug.log
```

With a quick Google search I found [this](https://github.com/APSL/react-native-version-number/issues/13#issuecomment-338965208) answer, according to which the maintainer has to remove the `.git` directory from the node module.

# Workaround

According to [this](https://github.com/APSL/react-native-version-number/issues/13#issuecomment-341059894), after executing `npm i midi-parser-js`, go to the subdir `<project-root>/node_modules/midi-parser-js/` and delete the `.git` directory. Afterwards - for good measure - execute `npm i` once again to finish the module installation.

Or simply execute this from your project root directory:
```bash
rm -rf node_modules/midi-parser-js/.git && npm i && echo "woop woop"
```

**Comment by colxi** [comment]
I've added a `.npmignore` file that prevents the `/.git `directory to be included in the package. And published the changes. The problem should be fixed now.

Thanks for reporting , and  for your research, and effort.
Let me know if my changes solved the problem.

**Comment by colxi** [comment]
After performing some tests, the problem does not manifest anymore, I asume it's been fixed. I close this issue.

**Comment by OliverHabersetzer** [comment]
Oh sorry - didn't check my mail. Seems to work now :D

**Comment by colxi** [comment]
Thanks for the feedback ;)
