### ISSUE TITLE
Readme is not clear on how to import

### ISSUE THREAD

**Issue by fheyen** [colxi/midi-parser-js#16]
Hi, thanks for the great tool!

I'm using React and wanted to import it via
`import { MidiParser } from 'midi-parser-js';`
as the readme says, but it did only work with
`import MidiParser from 'midi-parser-js';`.

I'm not sure if this is only relevant for React users or also WebPack etc., but it might be worth mentioning this in the readme, as it took me some minutes to figure that out.

**Comment by jdevries3133** [comment]
I am also working with this module in React and just went through a headache just trying to import it. For some reason, `import MidiParser from 'midi-parser-js';` works for me too, although looking at `src/midi-parser.js`, I see that the module is not exported by default... I'm confused as to why the default import works while the named import does not, but I had the same experience.

**Comment by colxi** [comment]
Thanks for reporting this. I've merged the PR where you provided the correction
