### ISSUE TITLE
deltaTime 16384

### ISSUE THREAD

**Issue by Yoshi1229** [colxi/midi-parser-js#2]
I have several midis with channels that starts at a certain part of the file, like after 20-30 seconds, but the deltaTime value is always 16384 and makes the channel's notes start early. Is 16384 the maximum?

**Comment by Yoshi1229** [comment]
[01 - Once Upon a Time.zip](https://github.com/colxi/midi-parser-js/files/1308309/01.-.Once.Upon.a.Time.zip)


channel 2 event 3 in this midi

**Comment by colxi** [comment]
I just see one event at deltatime 16384 , in that file. St's been aplied a new patch to the library, can you tests it again?

**Comment by Yoshi1229** [comment]
sorry for late reply
i tested it again and now all the event types seems to be note-on only?
the types all became 9, and the deltaTime seems still weird.
