### ISSUE TITLE
How can I use this data?

### ISSUE THREAD

**Issue by Justiniscoding** [colxi/midi-parser-js#28]
I have installed the package and have it reading a midi file, but I do not know how I can use the data. I am a noob to all things audio related, and am trying to play a song from a midi file. I am wondering, what are midi events? What is the data in them? What part of the data structure is the actual music notes? What is delta time? What s the type in midi events? 

Thanks, I hope all my questions can be answered!

**Comment by HMYang33** [comment]
i'm confused , too. have you got progress on this?

**Comment by Justiniscoding** [comment]
@HMYang33 I ended up using a different library, called "midi-player-js". You can find the github repo at https://github.com/grimmdude/MidiPlayerJS. It makes it *pretty* easy to read the audio data, and is working well with my project
