### ISSUE TITLE
Only note-off (9) events

### ISSUE THREAD

**Issue by JackPoteYes** [colxi/midi-parser-js#4]
On the parsed track, all the note events are type 9, never type 8. However when I open in a midi sequencer, I see it shouldn't be the case, the notes finish at some point.
See here, we the default example provided by default, from the chrome's console:

`{deltaTime: 1, type: 9, channel: 0, data: Array(2)}
2601
:
{deltaTime: 1, type: 9, channel: 0, data: Array(2)}
2602
:
{deltaTime: 2, type: 9, channel: 0, data: Array(2)}
2603
:
{deltaTime: 3, type: 9, channel: 0, data: Array(2)}
2604
:
{deltaTime: 36, type: 9, channel: 0, data: Array(2)}
2605
:
{deltaTime: 1, type: 9, channel: 0, data: Array(2)}
2606
:
{deltaTime: 0, type: 9, channel: 0, data: Array(2)}
2607
:
{deltaTime: 0, type: 9, channel: 0, data: Array(2)}
2608
:
{deltaTime: 3, type: 9, channel: 0, data: Array(2)}
2609
:
{deltaTime: 0, type: 9, channel: 0, data: Array(2)}
2610
:
{deltaTime: 11, type: 9, channel: 0, data: Array(2)}
2611
:
{deltaTime: 0, type: 9, channel: 0, data: Array(2)}
2612
:
{deltaTime: 0, type: 9, channel: 0, data: Array(2)}
2613
:
{deltaTime: 1, type: 9, channel: 0, data: Array(2)}
2614
:
{deltaTime: 4, type: 9, channel: 0, data: Array(2)}
2615
:
{deltaTime: 3, type: 9, channel: 0, data: Array(2)}
2616
:
{deltaTime: 33, type: 9, channel: 0, data: Array(2)}
2617
:
{deltaTime: 1, type: 9, channel: 0, data: Array(2)}
2618
:
{deltaTime: 2, type: 9, channel: 0, data: Array(2)}
2619
:
{deltaTime: 0, type: 9, channel: 0, data: Array(2)}
2620
:
{deltaTime: 1, type: 9, channel: 0, data: Array(2)}
2621
:
{deltaTime: 5, type: 9, channel: 0, data: Array(2)}
2622
:
{deltaTime: 3, type: 9, channel: 0, data: Array(2)}
2623
:
{deltaTime: 2, type: 9, channel: 0, data: Array(2)}
2624
:
{deltaTime: 0, type: 9, channel: 0, data: Array(2)}
2625
:
{deltaTime: 1, type: 9, channel: 0, data: Array(2)}
2626
:
{deltaTime: 5, type: 9, channel: 0, data: Array(2)}
2627
:
{deltaTime: 6, type: 9, channel: 0, data: Array(2)}
2628
:
{deltaTime: 4, type: 9, channel: 0, data: Array(2)}
2629
:
{deltaTime: 1, type: 9, channel: 0, data: Array(2)}
2630
:
{deltaTime: 27, type: 9, channel: 0, data: Array(2)}
2631
:
{deltaTime: 1, type: 9, channel: 0, data: Array(2)}
2632
:
{deltaTime: 0, type: 9, channel: 0, data: Array(2)}
2633
:
{deltaTime: 10, type: 9, channel: 0, data: Array(2)}
2634
:
{deltaTime: 1, type: 9, channel: 0, data: Array(2)}
2635
:
{deltaTime: 1, type: 9, channel: 0, data: Array(2)}
2636
:
{deltaTime: 4, type: 9, channel: 0, data: Array(2)}
2637
:
{deltaTime: 2, type: 9, channel: 0, data: Array(2)}
2638
:
{deltaTime: 9, type: 9, channel: 0, data: Array(2)}
2639
:
{deltaTime: 11, type: 9, channel: 0, data: Array(2)}
2640
:
{deltaTime: 12, type: 9, channel: 0, data: Array(2)}
2641
:
{deltaTime: 1, type: 9, channel: 0, data: Array(2)}
2642
:
{deltaTime: 0, type: 9, channel: 0, data: Array(2)}
2643
:
{deltaTime: 2, type: 9, channel: 0, data: Array(2)}
2644
:
{deltaTime: 1, type: 9, channel: 0, data: Array(2)}
2645
:
{deltaTime: 9, type: 9, channel: 0, data: Array(2)}
2646
:
{deltaTime: 1, type: 9, channel: 0, data: Array(2)}
2647
:
{deltaTime: 1, type: 9, channel: 0, data: Array(2)}
2648
:
{deltaTime: 4, type: 9, channel: 0, data: Array(2)}
2649
:
{deltaTime: 0, type: 9, channel: 0, data: Array(2)}
2650
:
{deltaTime: 15, type: 9, channel: 0, data: Array(2)}
2651
:
{deltaTime: 16, type: 9, channel: 0, data: Array(2)}
2652
:
{deltaTime: 5, type: 9, channel: 0, data: Array(2)}
2653
:
{deltaTime: 0, type: 9, channel: 0, data: Array(2)}
2654
:
{deltaTime: 2, type: 9, channel: 0, data: Array(2)}
2655
:
{deltaTime: 2, type: 9, channel: 0, data: Array(2)}
2656
:
{deltaTime: 8, type: 9, channel: 0, data: Array(2)}
2657
:
{deltaTime: 5, type: 9, channel: 0, data: Array(2)}`

**Comment by colxi** [comment]
it's been 6 months since you opened this issue, but i never got the details needed to consider this as a bug.
I close the issue, assuming my previous comment explains your situation.
