### ISSUE TITLE
Error in readIntVLV?

### ISSUE THREAD

**Issue by tengyifei** [colxi/midi-parser-js#5]
https://github.com/colxi/midi-parser-js/blob/master/src/midi-parser.js#L182

```javascript
for(var dt = 1; dt <= FirstBytes.length; dt++){
    value = FirstBytes[FirstBytes.length - dt] * Math.pow(128, dt);
}
```

Looks like `value` will be overwritten on each iteration.

**Comment by colxi** [comment]
Fixed! Thhanks
