### ISSUE TITLE
wrong parsing of certain files

### ISSUE THREAD

**Issue by ig1na** [colxi/midi-parser-js#7]
hi, 

i've found several issues while trying to parse certain midi files for which I have no issue in other midi programs : 
![issue](https://user-images.githubusercontent.com/15821391/39523977-be5b4e34-4e17-11e8-82ca-4dd1457e5852.PNG)
As you can see, midi-parser-js says there are 10 tracks, but only show two, and they contain no note...

I have no issue at all when I load it into MidiEditor or music21 : 

![issue2](https://user-images.githubusercontent.com/15821391/39524015-ea4a047c-4e17-11e8-85af-25b7ba52d204.PNG)

I don't know what's causing this

**Comment by colxi** [comment]
cpuld you attach the file, so i can debug using it  ?

**Comment by ig1na** [comment]
yes of course sorry, here it is 
[christmas.zip](https://github.com/colxi/midi-parser-js/files/1968800/christmas.zip)

**Comment by ig1na** [comment]
ok so it seems I managed to fix this, the issue was that only 4 bytes were read from an SMPTE Offset Meta-event, where 5 bytes should be read so I modified this part of the code : 

![issue2](https://user-images.githubusercontent.com/15821391/39555157-41898ac8-4e77-11e8-8d16-9ba91a53b9ec.PNG)

to this : 

![issue](https://user-images.githubusercontent.com/15821391/39555106-04cbeb58-4e77-11e8-85f1-97d3944202d3.PNG)
