### ISSUE TITLE
Meta Events 0x04, 0x05, and 0x07 not handled

### ISSUE THREAD

**Issue by kmf123kmf** [colxi/midi-parser-js#9]
The text events 0x04 (Instrument Name), 0x05 (Lyrics), and 0x07 (Cue point) are missing from the meta handling routine.  This causes them to be parsed as integer values which can lead to incorrect parsing of  the next event.  The fix is extremely simple; just add them in at line 251-252.

Test file attached.  Track 1's second event is meta 0x04 with data "Piano".   
[LetItGo.zip](https://github.com/colxi/midi-parser-js/files/2810755/LetItGo.zip)

**Comment by colxi** [comment]
Thanks for the  contribution!
I've already applied the proposed changes
